(function() {
  const array = [
    [
        "Beroende på",
        "Efter en helhetsbedömning av",
        "Enligt",
        "Förutsatt",
        "Genom",
        "Givet",
        "Grundat på",
        "I enlighet med",
        "I förhållande till",
        "I ljuset av",
        "I och med",
        "I samverkan med",
        "Jämfört med",
        "Med beaktande av",
        "Med hänsyn till",
        "Med hänsynstagande till",
        "Med hänvisning till",
        "Med tanke på",
        "Med tanke på",
        "Med utgångspunkt i",
        "Oavsett",
        "Oberoende av",
        "På grund av",
        "På grundval av",
        "Sett mot bakgrund av",
        "Utan hänsyn till",
    ],
    [
        "en aktuell",
        "en bristande",
        "en grundläggande",
        "en ihållande",
        "en implicit",
        "en inkluderande",
        "en inte försumbar",
        "en integrerad",
        "en kommunikativ",
        "en kostnadseffektiv",
        "en långsiktig",
        "en lönsam",
        "en löpande",
        "en minskande",
        "en ökad",
        "en optimal",
        "en övergripande",
        "en proaktiv",
        "en resultatorienterad",
        "en särskild",
        "en signifikant",
        "en sömlös",
        "en tilltagande",
        "en tvärvetenskaplig",
    ],
    [
        "agenda",
        "arbetsledningsinsats",
        "arbetsmodell",
        "avvägning",
        "begrundan",
        "effekt",
        "effektivisering",
        "implementering",
        "innovation",
        "insats",
        "kvalitetshöjning",
        "kvalitetssäkring",
        "målsättning",
        "måluppfyllnad",
        "mobilitet",
        "organisation",
        "problematik",
        "problemlösning",
        "redovisning",
        "resursanvändning",
        "struktur",
        "tidsaspekt",
        "träffsäkerhet",
        "utveckling",
    ],
    [
        "balanseras",
        "beaktas",
        "dokumenteras",
        "erhålls",
        "förankras",
        "genereras",
        "härleds",
        "identifieras",
        "initieras",
        "kommuniceras",
        "konkretiseras",
        "lokaliseras",
        "normaliseras",
        "maximeras",
        "påbörjas",
        "realiseras",
        "revitaliseras",
        "stabiliseras",
        "stärks",
        "stimuleras",
        "synliggörs",
        "tillgängliggörs",
        "tillvaratas",
        "utökas",
        "verkställs",
    ],
    [
        "betydelsen",
        "erfarenhetsutbytet",
        "fokuseringen",
        "förankringen",
        "incitamentet",
        "informationsflödet",
        "insatsen",
        "instrumentet",
        "kompetenshöjningen",
        "kostnadskostymen",
        "kriterierna",
        "kunskaperna",
        "närvaron",
        "policyn",
        "ökningen",
        "potentialen",
        "relationerna",
        "resultaten",
        "riskfaktorerna",
        "särarten",
        "scenariot",
        "spetskompetensen",
        "stimulansåtgärden",
        "strategin",
        "synergieffekten",
        "uppföljningen",
    ],
    [
        "baserat nästintill på",
        "beroende på",
        "eller med andra ord:",
        "i anknytning till",
        "i förhållande till",
        "i förlängningen av",
        "i linje med",
        "i motsätting till",
        "i relation till",
        "inom ramen för",
        "inom",
        "kring",
        "med avseende på",
        "med hänsyn till",
        "med sikte på",
        "mot bakgrund av",
        "på samma sätt som",
        "på tvärs med",
        "parallellt med",
        "som en följd av",
        "till skillnad från",
        "utifrån",
        "utöver",
        "vad gäller",
        "vad gäller",
        "via",
    ],
    [
        "analysutredningen",
        "behoven",
        "beskaffenheten",
        "en samlad bedömning",
        "förhållandena",
        "helhetsbedömningen",
        "implementeringen",
        "kärnverksamheten",
        "konceptet",
        "konsekvensaspekten",
        "lösningen",
        "maktanalysen",
        "målet",
        "parametrarna",
        "problemet",
        "resultatuppnåelsen",
        "resurserna",
        "resursinsatsen",
        "riktlinjerna",
        "särarten",
        "satsningsområdet",
        "tillhandahållandet",
        "utvärderingen",
        "värdena",
        "väsentligheten",
        "verklighetsfokuset",
        "visionen",
    ],
  ]

  const generateBuzzphrase = () => {
    return array.reduce((buzzphrase, phrases) => {
      return buzzphrase += " " + phrases[Math.floor(Math.random() * phrases.length)]
    }, "")
  }

  const init = () => {
    const buzzphraseElement = document.getElementById("buzzphrase")
    const generateBuzzphraseElement = document.getElementById("generateBuzzphrase")

    buzzphraseElement.innerHTML = ['"', generateBuzzphrase().trim(), '"'].join('')

    generateBuzzphraseElement.addEventListener("click", function() {
      buzzphraseElement.innerHTML = ['"', generateBuzzphrase().trim(), '"'].join('')
    })
  }

  document.addEventListener('DOMContentLoaded', init)
})()
